language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t kocsisstefan/docker-react -f Dockerfile.dev .



script:
  - docker run -e CI=true kocsisstefan/docker-react npm run test -- --coverage